export const FETCHCOURSES = 'FETCHCOURSES';
export const FETCHCATE = 'FETCHCATE';
export const FETCHFRONTEND='FETCHFRONTEND';
export const FETCHFULLSTACK='FETCHFRONTEND';
export const FETCHMOBILE='FETCHMOBILE';
export const FETCHBACKEND='FETCHBACKEND';
export const FETCHMINDSET='FETCHMINDSET';
export const FETCHDESIGN='FETCHDESIGN';
export const FETCHCREDENTIALS='FETCHCREDENTIALS'
export const FETCHLOGGOUT='FETCHLOGGOUT'
export const FETCHCOURSEDETAIL='FETCHCOURSEDETAIL'

//
export const FETCHUSERINFO = 'FETCHUSERINFO';